# Step 1: Build the app
FROM node:16 AS build

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy the rest of the app
COPY . .

# Step 2: Expose the port and start the app
EXPOSE 8081

CMD ["npm", "start"]
